UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

#oferta:
#    resource: "@OfertaBundle/Resources/config/routing.yml"
#    prefix:   /

oferta:
    path:     /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }

#_paginas_estaticas:
#    resource: routing_paginas.yml
#    prefix:   /pagina
#    defaults: { _controller: FrameworkBundle:Template:template }
#  ESTO NO VA, dejo pagina_estatica
pagina_estatica:
    path:     /sitio/{pagina}
    defaults: { _controller: OfertaBundle:Sitio:estatica }

# Ruta completa de la portada (con el slug de la ciudad)
_portada:
     path:     /
     defaults: { _controller: FrameworkBundle:Redirect:redirect, route: portada, ciudad: '%cupon.ciudad_por_defecto%' }
 
# Ruta de la portada completa del sitio (con _locale y el slug de la ciudad)
portada:
    path:     /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada }

